import { Inter } from "next/font/google";
import "./globals.css";
import { createTheme, MantineProvider } from "@mantine/core";

// core styles are required for all packages
import "@mantine/core/styles.css";

import Header from "@/components/LayoutElement/Header";
import Footer from "@/components/LayoutElement/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CGS",
  description: "Generated by create next app",
};

const theme = createTheme({
  /** Put your mantine theme override here */
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <Header />
          <div>{children}</div>
          <Footer/>
        </MantineProvider>
      </body>
    </html>
  );
}
